---
title: Disable Settings Tips
description: Disables Settings tips for QoL
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\PolicyManager\default\Settings\AllowOnlineTips'
    value: 'value'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'AllowOnlineTips'
    data: '0'
    type: REG_DWORD