---
title: Restore Old Context Menu
description: Restores the old context menu in Windows 11
privilege: TrustedInstaller
builds: [ '>=22000' ]
actions:
  - !registryValue:
    path: 'HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32'
    value: ''
    data: ''
    type: REG_SZ
