---
title: Disable Program Compatibility Assistant (PCA)
description: Disables PCA for QoL and privacy
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat'
    value: 'AITEnable'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat'
    value: 'AllowTelemetry'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat'
    value: 'DisableEngine'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat'
    value: 'DisableInventory'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat'
    value: 'DisablePCA'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat'
    value: 'DisableUAR'
    data: '1'
    type: REG_DWORD
